version: '3.2'

services:
  redis:
    image: redis
    volumes:
      - react-slack-clone-redisdb:/data
    container_name: slackredis
    restart: unless-stopped

  mongo:
    image: mongo
    volumes:
      - react-slack-clone-mongodb:/data/db
    ports:
      - 27017:27017
    container_name: slackmongo
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq
    volumes:
      - react-slack-clone-rabbitmq:/var/lib/rabbitmq
    container_name: slackmq
    restart: unless-stopped
  
  nodechatbot:
    image: jadiego/react-slack-clone-chatbot
    build: ./chatbot/
    environment:
      - WITAITOKEN
      - MONGOADDR=mongodb://mongo:27017
    depends_on:
      - mongo
    container_name: slackchatbot
    restart: unless-stopped
  
  gomessaging:
    image: jadiego/react-slack-clone-apimessaging
    build: ./messaging/
    environment:
      - DBADDR=mongodb://mongo:27017
      - MQADDR=amqp://rabbitmq:5672
      - TLSKEY=/tls/privkey.pem
      - TLSCERT=/tls/fullchain.pem
      - SESSIONKEY
    volumes:
      - ./tls/fullchain.pem:/tls/fullchain.pem:ro
      - ./tls/privkey.pem:/tls/privkey.pem:ro
    depends_on:
      - mongo
      - rabbitmq
    container_name: slackmessagesms
    restart: unless-stopped

  gogateway:
    image: jadiego/react-slack-clone-apigateway
    build: ./gateway/
    ports:
      - 443:443
    environment:
      - MSGADDR=gomessaging:80
      - CHATBOTADDR=nodechatbot:80
      - REDISADDR=redis:6379
      - DBADDR=mongodb://mongo:27017
      - MQADDR=amqp://rabbitmq:5672
      - TLSKEY=/tls/privkey.pem
      - TLSCERT=/tls/fullchain.pem
      - SESSIONKEY
    volumes:
      - ./tls/fullchain.pem:/tls/fullchain.pem:ro
      - ./tls/privkey.pem:/tls/privkey.pem:ro
    depends_on:
      - rabbitmq
      - mongo
      - redis
      - gomessaging
    container_name: slackapigateway
    restart: unless-stopped


volumes:
  react-slack-clone-mongodb:
  react-slack-clone-redisdb:
  react-slack-clone-rabbitmq:
