version: '3.2'

services:
  redis:
    image: redis
    volumes:
      - react-slack-clone-redisdb:/data
    container_name: slackredis
    restart: unless-stopped

  mongo:
    image: mongo
    volumes:
      - react-slack-clone-mongodb:/data/db
    container_name: slackmongo
    restart: unless-stopped

  goapigateway:
    image: jadiego/react-slack-clone-apigateway
    build: ./gateway/
    ports:
      - 443:443
      - 4000:443 #forwards https://localhost:4000 on local computer to port 443 on container
    environment:
      - REDISADDR=redis:6379
      - DBADDR=mongo:27017
      - SESSIONKEY
      - TLSKEY=/tls/privkey.pem
      - TLSCERT=/tls/fullchain.pem
    volumes:
      - ./tls/fullchain.pem:/tls/fullchain.pem:ro
      - ./tls/privkey.pem:/tls/privkey.pem:ro
    depends_on:
      - mongo
      - redis
    container_name: slackapigateway
    restart: unless-stopped


volumes:
  react-slack-clone-mongodb: {}
  react-slack-clone-redisdb: {}
